echo '### publish'
echo ''
echo '```'
echo "$(bundle exec bin/pact-broker help publish)"
echo '```'
echo ''
echo '### create-version-tag'
echo ''
echo '```'
echo "$(bundle exec bin/pact-broker help create-version-tag)"
echo '```'
echo ''
echo '### can-i-deploy'
echo ''
echo '*This feature is in beta release, and backwards compatibility is NOT guaranteed.*'
echo 'You will need the latest version of the Pact Broker for this feature to work.'
echo ''
echo '```'
echo "$(bundle exec bin/pact-broker help can-i-deploy)"
echo '```'