name: Delete application branch in Pactflow

on:
  delete

jobs:
  delete-branch-in-pactflow:
    name: delete
    runs-on: ubuntu-latest

    steps:
      - uses: pactflow/actions/delete-branch@3074b72c0df6af10087afccfa6f91e2308dc151c  # v2
        with:
          broker_url: "https://pact-foundation.pactflow.io"
          token: ${{ secrets.PACT_BROKER_TOKEN_PACT_FOUNDATION }}
          application_name: "Pact Broker Client"
          branch: ${{ github.event.ref }}
